version: '3.8'

services:
  image-service:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./storage:/app/storage  # 持久化儲存
    environment:
      - STORAGE_PATH=/app/storage
      - MAX_FILE_SIZE=10485760  # 10MB
      - MAX_BATCH_SIZE=100
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  storage_data:
    driver: local